### ISSUE TITLE
List of user guide issues

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/user_guide#5]
- [ ] demonstrate re-usable custom types https://github.com/common-workflow-language/common-workflow-language/issues/438
- [ ] demonstrate use of scicrunch.org to find IRIs for SoftwareRequirement https://github.com/common-workflow-language/common-workflow-language/issues/437
- [ ] add `#!/usr/bin/env cwl-runner` to user guide and examples https://github.com/common-workflow-language/common-workflow-language/issues/436
- [ ] document optional enum syntax https://github.com/common-workflow-language/common-workflow-language/issues/392
- [ ] document in user guide that multiple parameter references and string concatenation are possible without InlineJavascript https://github.com/common-workflow-language/common-workflow-language/issues/389
- [ ] Review SMC_RNA docs for inclusion with user guide https://github.com/common-workflow-language/common-workflow-language/issues/388
- [ ] add (link to) reference implementation installation instructions https://github.com/common-workflow-language/common-workflow-language/issues/367
- [ ] better document the 'default' and 'valueFrom' fields on WorkflowStepInput https://github.com/common-workflow-language/common-workflow-language/issues/359
- [ ] capture docker+CWL best practices from Denis Yuen et al. https://github.com/common-workflow-language/common-workflow-language/issues/347
- [ ] Tutorial inconcistencies https://github.com/common-workflow-language/common-workflow-language/issues/318
- [ ] secondaryFiles https://github.com/common-workflow-language/common-workflow-language/issues/270
- [ ] how to reuse custom record types https://github.com/common-workflow-language/common-workflow-language/issues/241
- [ ] Apply the readme checklist https://github.com/common-workflow-language/common-workflow-language/issues/223
- [ ] rework Record inputs, dependent and mutually exclusive parameters https://github.com/common-workflow-language/common-workflow-language/issues/202

**Comment by evan-wehi** [comment]
I think even before getting into syntax details the user guide needs to give a much better conceptual description of the CWL objects and in general terms how they might be constructed and manipulated. Then the logic behind why CWL is the way is will be much clearer and will help people like me solve specific problems. For example, I hit the common issue that bam indexes need to travel along side the bam files even though the tools don't explicitly reference them. I found the solution on biostars (I think). This is it:
```
  #
  # Gather human bam and index into one dependency
  #
  gather:
    run:
      class: ExpressionTool

      inputs:
        bamFile:
          type: File
        bamIndex:
          type: File

      outputs:
        combined:
          type: File

      expression: >
        ${
          var ret = inputs.bamFile;
          ret["secondaryFiles"] = [
            inputs.bamIndex
          ];
          return {"combined" : ret};
        }

    in:
      bamFile:
        source: sort-human/sorted
      bamIndex:
        source: index-human/index

    out: [combined]
```

This does makes not sense to me. It seems to be javascript manipulating an internal CWL object. Without a model of what's going in CWL not only do I not understand this but I have no way to solve similar issues (of which there are many).

CWL is very rich, the user guide also needs much more coverage of its features. In particular, what can be done with JS needs more coverage. (Please bear in mind, some people are allergic to JS.)

**Comment by tobyhodges** [comment]
Thanks @evan-wehi this is a good point. And I agree completely about the need for more coverage of features in general.

I'm nearly done with the more functional aspects of migrating the gentle intro material, at which point I hope that we can quickly begin to add additional sections and flesh out what is there already.
